name: Publish Client

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'limit-lens-client/**'

permissions:
    contents: write
    pull-requests: write
    packages: write
    issues: write 

jobs:
  publish-client:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Publish OpenAPI Rust Client
        working-directory: ./limit-lens-client
        run: |
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }} 