name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write 

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Install Rust
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Generate OpenAPI Specification
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin generate_openapi -- --output ./openapi.json
          
      - name: Generate Rust OpenAPI Client
        if: ${{ steps.release.outputs.release_created }}
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
            -i /local/openapi.json \
            -g rust \
            -o /local/limit-lens-client
          
      - name: Publish OpenAPI Rust Client
        if: ${{ steps.release.outputs.release_created }}
        working-directory: ./limit-lens-client
        run: |
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }} 