name: Release Please and Generate Client

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write 

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Install Rust
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Generate OpenAPI Specification
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin generate_openapi -- --output ./openapi.json
          
      - name: Generate Rust OpenAPI Client
        if: ${{ steps.release.outputs.release_created }}
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
            -i /local/openapi.json \
            -g rust \
            -o /local/limit-lens-client \
            --skip-validate-spec
          
      - name: Create PR for client updates
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update OpenAPI client"
          title: "chore: update OpenAPI client for release ${{ steps.release.outputs.tag_name }}"
          body: "This PR updates the OpenAPI client based on the latest API changes."
          branch: "update-openapi-client" 